name: ci

on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Build
        run: |
          sbt buildTool
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Seekprog
          path: target/scala-3.3.1/Seekprog.zip
  deploy:
    permissions:
      pages: write
      id-token: write
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: Seekprog
      - run: |
          mkdir pages
          cp Seekprog.zip pages/
          cp tool.properties pages/Seekprog.txt
      - uses: actions/upload-pages-artifact@v2
        with:
          path: pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
